"""add member_invited to action enum

Revision ID: 0f1da1c359ef
Revises: fceb5c7a32c4
Create Date: 2026-08-22 09:39:37.935882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1da1c359ef'
down_revision: Union[str, Sequence[str], None] = 'fceb5c7a32c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE actionenum ADD VALUE 'member_invited'")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
